version: '3.8'

services:
  node_backend:
    container_name: node_backend
    image: cosigning-server
    build:
      context: .
    ports:
      - '8080:80'
    environment:
      - PGUSER=cosigning-server
      - PGPASSWORD=12345
      - PGDATABASE=defaultdb
      - PGHOST=db # NAME OF THE SERVICE
    depends_on:
      - db
  db:
    container_name: db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=cosigning-server
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=defaultdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
